local_backend: true

logo_url: /logo.svg

backend:
    name: github
    branch: main
    repo: loicginoux/SDprices-front
    base_url: https://sveltia-cms-auth.lginoux.workers.dev
    automatic_deployments: false

media_folder: "public/blog/images"
public_folder: "/blog/images"

i18n:
    structure: "multiple_folders"
    locales: ["en"]
    default_locale: "en"

collections:
    - name: "posts"
      i18n: true
      label: "Blog Posts"
      folder: "src/content/blog"
      create: true
      delete: true
      fields:
          - name: "title"
            widget: "string"
            label: "Post Title"
            i18n: true
          - label: "Draft"
            name: "draft"
            widget: "boolean"
            i18n: "duplicate"
          - label: "Tags"
            name: "tags"
            widget: "list"
            i18n: true
          - label: "Author"
            name: "author"
            widget: "string"
            i18n: "duplicate"
            required: false
          - label: "Image"
            name: "image"
            widget: "object"
            i18n: true
            fields:
                - { label: Source, name: src, widget: image, i18n: "duplicate" }
                - { label: Alt Text, name: alt, widget: string, i18n: true }
          - label: "Snippet"
            name: "snippet"
            widget: "text"
            i18n: true
          - label: "Publish Date"
            name: "publishDate"
            widget: "datetime"
            format: "YYYY-MM-DD HH:mm"
            i18n: "duplicate"
          - label: "Category"
            name: "category"
            widget: "select"
            options: ["Tutorials", "News", "Reviews", "Frameworks", "Others"]
            i18n: "duplicate"
          - name: "body"
            widget: "markdown"
            label: "Post Body"
            i18n: true
    - name: "faqs"
      i18n: true
      label: "FAQs"
      folder: "src/content/faq"
      create: true
      delete: true
      fields:
          - name: "title"
            widget: "string"
            label: "Post Title"
            i18n: true
          - name: "body"
            widget: "markdown"
            label: "Post Body"
            i18n: true
